cp patric-libs/build/patric-libs.jar            				~/jboss_patric/deploy/patric-war/
cp patric-common/build/patric-common.war        				~/jboss_patric/deploy/patric-war/
cp patric-diseaseview/build/patric-diseaseview.war 				~/jboss_patric/deploy/patric-war/
cp patric-hpi/build/patric-hpi.war              				~/jboss_patric/deploy/patric-war/
cp patric-jbrowse/build/patric-jbrowse.war      				~/jboss_patric/deploy/patric-war/
cp patric-mashup/build/patric-mashup.war        				~/jboss_patric/deploy/patric-war/
cp patric-overviews/build//patric-overviews.war 				~/jboss_patric/deploy/patric-war/
cp patric-pathways/build/patric-pathways.war    				~/jboss_patric/deploy/patric-war/
cp patric-phylogeny/build/patric-phylogeny.war  				~/jboss_patric/deploy/patric-war/
cp patric-searches-and-tools/build/patric-searches-and-tools.war ~/jboss_patric/deploy/patric-war/
cp patric-static/build/patric-static.war        				~/jboss_patric/deploy/patric-war/
cp patric-transcriptomics/build/patric-transcriptomics.war 		~/jboss_patric/deploy/patric-war/
cp patric-proteinfamily/build/patric-proteinfamily.war 			~/jboss_patric/deploy/patric-war/
